baseURL = "https://crackeer.github.io/"
languageCode = "zh-cn"
title = "记录生活，记录爱"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = false
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "好站"
    url = "/website/"
    weight = 2

  [[menu.main]]
    name = "最近"
    url = "/recent/"
    weight = 3

  [[menu.main]]
    name = "我"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "疯子"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "记录是变好的开始"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""


[params.social]
    GitHub = "crackeer"
    Email   = "creepykid@qq.com"
